# Generated by Django 5.0.6 on 2024-07-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='subtasks',
            field=models.CharField(blank=True, default='No subtasks', max_length=100),
        ),
    ]
