# Generated by Django 5.0.6 on 2024-07-13 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_alter_taskitem_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='assignedTo',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='assignedToID',
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='colors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='subtasks',
            field=models.TextField(blank=True, default='No subtasks'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='assignedToID',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
