# Generated by Django 5.0.6 on 2024-09-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_alter_contacts_contactassignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
