# Generated by Django 5.0.6 on 2024-07-13 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_alter_taskitem_assignedto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='assignedToID',
            field=models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
