# Generated by Django 5.0.6 on 2024-09-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_alter_taskitem_assignedtoid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='subtasks',
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_checked', models.BooleanField(default=False)),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join.taskitem')),
            ],
        ),
    ]
